-- A lexical scanner generated by aflex
with text_io, phelps_dfa, phelps_io;
use text_io, phelps_dfa, phelps_io;
--# line 1 "phelps.l"
--# line 13 "phelps.l"

with phelps_tokens, declaracions.arbre, semantica.construccio_arbre;
use phelps_tokens, declaracions.arbre, semantica.construccio_arbre;

package analitzador_lexic is
   function yylex return token;
end analitzador_lexic;